# Generated by Django 5.0.2 on 2024-06-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginScreens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='Password',
            field=models.CharField(max_length=50),
        ),
    ]
